name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore
        run: dotnet restore ./Neighbor.API.sln
        
      - name: Build
        run: dotnet build ./Neighbor.API.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./Neighbor.API.sln --configuration Release --no-build
